services:
    best_it_ct_clean_up.command.cleanup_command:
        class: BestIt\CtCleanUpBundle\Command\CleanupCommand
        arguments:
            - '@best_it_ct_clean_up.commercetools.client'
            - '@best_it_ct_clean_up.logger'
            - '%best_it_ct_clean_up.predicates%'
        tags:
            - { name: console.command }


    best_it_ct_clean_up.commercetools.client:
        class: Commercetools\Core\Client
        factory: ['BestIt\CtCleanUpBundle\ClientFactory', createClient ]
        arguments:
        -   {
                client_id: '%best_it_ct_clean_up.commercetools.client.id%',
                client_secret: '%best_it_ct_clean_up.commercetools.client.secret%',
                project: '%best_it_ct_clean_up.commercetools.client.project%',
                scope: '%best_it_ct_clean_up.commercetools.client.scope%'
            }
        - '@cache.app'
